### ISSUE TITLE
Render images on supported terminals.

### ISSUE THREAD

**Issue by ghost** [tulir/gomuks#103]
Certain terminals, such as Kitty, support rendering images inside the terminal. In these conditions I think the image should be rendered.

**Comment by ReK2Fernandez** [comment]
+1

**Comment by abrahimladha** [comment]
Ranger supports this by making w3m do all the work with w3mmingdisplay. If gomuks follows a similiar idea, it might not be too hard to implement.

**Comment by foresto** [comment]
Related: The vte library now [supports sixel graphics](https://gitlab.gnome.org/GNOME/vte/-/issues/253#note_886802), so terminal programs built with that library will probably have it before long. This includes gnome-terminal, xfce4-terminal, and others.

**Comment by Tycho-S** [comment]
Sorry for opening a duplicate earlier, I closed it already.

I found another library in go that can do this (unlike vte that's in C++)
https://github.com/BourgeoisBear/rasterm

Additionally to sixel it can also use the kitty protocol. One thing it doesn't do is block rendering like the current library though, sadly.

**Comment by Aleksanaa** [comment]
https://github.com/mattn/go-sixel
That's a go module

**Comment by reynoldsme** [comment]
As far as I understand, before any high resolution image format can be included in-band in gomuks it will need to be implemented in the tcell TUI library that gomuks uses. There is an open PR https://github.com/gdamore/tcell/pull/436 that exposes interfaces in tcell to implement arbitrary graphics protocols as plugins and the PR author has a really cool demo showing a tcell sixel implementation. https://github.com/diamondburned/tcell-sixel Unfortunately, there doesn't seem to have been any activity on the PR recently.

I say "in-band" meaning, the images are sent by the application and displayed directly by the terminal emulator, because there is an alternative "out-of-band" approach, but it has downsides.

w3m-img https://packages.debian.org/sid/w3m-img and ueberzugi (now unmaintained) https://github.com/seebye/ provide raster images support by drawing over a terminal window via an external process. This bypasses the need for the terminal and and TUI library to directly support an image protocol, but doesn't work by default over SSH, and requires that the image drawing implementation support specific OSs and display managers.

https://github.com/mattn/go-sixel appears to work great for encoding sixel images, but at the moment there doesn't seem to be a good way to output those images in the gomuks UI.

**Comment by ferdinandyb** [comment]
There's also another approach to adding sixels to tcell since 436: https://github.com/gdamore/tcell/pull/602. Fingers crossed for some implementation to happen :)

**Comment by deonspengler** [comment]
I see [gdamore/tcell#602](https://github.com/gdamore/tcell/pull/602) has now been merged. Could someone please point me in the right direction with regards to gomuks, which source file currently handles the displaying of the ansi image. I would like to see if I get sixel to work in gomuks.

**Comment by reynoldsme** [comment]
> I see [gdamore/tcell#602](https://github.com/gdamore/tcell/pull/602) has now been merged. Could someone please point me in the right direction with regards to gomuks, which source file currently handles the displaying of the ansi image. I would like to see if I get sixel to work in gomuks.

https://github.com/tulir/gomuks/blob/master/ui/messages/filemessage.go#L179

**Comment by deonspengler** [comment]
> > I see [gdamore/tcell#602](https://github.com/gdamore/tcell/pull/602) has now been merged. Could someone please point me in the right direction with regards to gomuks, which source file currently handles the displaying of the ansi image. I would like to see if I get sixel to work in gomuks.
> 
> https://github.com/tulir/gomuks/blob/master/ui/messages/filemessage.go#L179

Thanks, I will give this try. First time working with go, I normally code in python.

**Comment by r3k2** [comment]
any news on this? :)

**Comment by benmordecai** [comment]
Another option may be to use ueberzugpp the way that ytfzf does for thumbnails

**Comment by coderkun** [comment]
The problem I have is that the mauview library does not support this. The currently implementation is based on chars via the `SetContent()` function but for Sixel we would need a separate method that uses something the following code (from the Sixel demo):

    	// Move the cursor to our draw position
	ti.TPuts(tty, ti.TGoto(sixelX, sixelY))
	// Draw the sixel data
	ti.TPuts(tty, img.data.String())
