### ISSUE TITLE
mismatching SHA-256 digest on downloading file

### ISSUE THREAD

**Issue by Midek** [tulir/gomuks#167]
I am running gomuks with encryption disabled, over pantalaimon.
In an encrypted room, when i try to open or download an image with `/open` or `/dl` gomuks throws out  "Failed to download media: mismatching SHA-256 digest" error
The thumbnail for the image is being rendered properly, and when i ctrl+left click with a mouse on the image, it displays in an image viewer properly.
 Expected result: gomuks downloads/opens the file with /open or /download file

**Comment by tulir** [comment]
I think Pantalaimon also forgets to strip the e2ee file info from the media. File info exists -> gomuks assumes it's an encrypted file, but pantalaimon serves the unencrypted file -> decrypting fails.

Media encryption in Matrix is fairly separate from message encryption and it's pure Go in gomuks, which is why it's always enabled.
