### ISSUE TITLE
Add an option to select autocompletion entry with mouse

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#204]
As discussed in https://github.com/tulir/gomuks/issues/198#issuecomment-683479457

**Comment by MayeulC** [comment]
Note: this means selecting the option trough clicking on it.

**Comment by wvffle** [comment]
> Note: this means selecting the option trough clicking on it.

 not necessarily

**Comment by MayeulC** [comment]
Well, I assumed that because the linked comment says:

> Clickable autocompletion options and cycling through options with tab can also be feature requests (in new issues)

And cyclable autocompletion is already asked for in #203. So I assumed this one was just clicking. I was sorting trough the issues and the difference between those two titles wasn't immediately apparent to me. Would you mind clarifying what you mean with "Add an option to select autocompletion entry" that isn't "cycling", nor clicking with a mouse? :)

**Comment by wvffle** [comment]
I totally forgot about that I created a separate issue for this, sorry ;p
