### ISSUE TITLE
Cannot use Ctrl+Up/Down or Alt+Up/Down to switch rooms in the TTY

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [tulir/gomuks#269]
When I'm in the TTY, I have to search for rooms with `ctrl+k` as opposed to switching between them with `ctrl+up` or `ctrl+down`.

**Comment by fmlatghor** [comment]
I noticed this too actually. I wonder what would cause it?

**Comment by mradigen** [comment]
I'm not very experienced with TTYs, but my guess would be that `alt` and `ctrl` shortcuts are captured by the TTY itself to perform keybinds like `ctrl + alt + F2` or `alt + left` to switch between TTYs. I suppose these are implemented for safety reasons so one could switch to another TTY if incase of any issue. Due to this, I don't think TTYs will allow to pass these modifier keys to the shell itself, and trying alternate ways to capture the modifier keys could be very dangerous (might prevent TTY switching).

**Comment by fmlatghor** [comment]
I think you're right actually. I remember this being the case with weechat, in that instance I just used ^p/^n.

-- 
Leo Coogan



14 Jun 2021, 06:24 by ***@***.***:

**Comment by pataquets** [comment]
I remember a while ago having problems with Ctrl-{left,right} for the shell readline editing on TTYs. I guess it's a TTY issue, not gomuks'. If you happen to confirm it and you find a solution, adding it to the docs would be nice for future users.
