### ISSUE TITLE
Wrong number of unread messages

### ISSUE THREAD

**Issue by SchweinDeBurg** [tulir/gomuks#285]
I've just built and packaged Gomux from the "master" branch and then joined the "#purple:matrix.org" room. Gomuks always shows that I have 22 unread messages. But if I go to the https://app.element.io/#/room/#purple:matrix.org - there is no such messages (and it is true). Other rooms (e.g. #matrix:matrix.org or even #gomuks:maunium.net) shows unread messages correctly. What could be the reason for this?

**Comment by foresto** [comment]
This happens to me as well, in small encrypted rooms. Gomuks gets stuck with a number in parentheses next to the room name, and it might take days or weeks before it gets cleared.

**Comment by motorto** [comment]
Can confirm it happens to me as well,

running `/clearcache` inside the room seems to do the trick at least for me

**Comment by broukema** [comment]
This bug seems very similar to #230 - I have this bug too.

I did `/clearcache` in one of the wrong-number-of-unread-messages rooms (an E2EE one), and after restarting `gomuks` and waiting about 5-10 minutes for the sync, my wrong-numbers-of-unread numbers disappeared from all the rooms with the wrong numbers of unread messages :).
