### ISSUE TITLE
Support for spaces

### ISSUE THREAD

**Issue by ptman** [tulir/gomuks#299]
At least read-only would be useful.

**Comment by SEbbaDK** [comment]
I was thinking one simple way of doing this could be via the existing tagging feature?
Possibly just automatically putting all rooms in a space under a tag. Since channels can be under multiple tags this might be enough?
However, displaying the space channel in a different way might be a nice addition.

**Comment by salarua** [comment]
What I'd like to see is for spaces to appear alongside rooms, but they would have some kind of icon to differentiate them. When navigated to, a list of rooms in the space would appear where the chat would otherwise be, and you can click on the room names to navigate to them. The pros of this approach are that the member list and topic are visible, but the con is that not all rooms would appear in the room list.

The other way I thought about was having spaces be drop-down menus in the room list. They would be collapsible, and subspaces can appear nested in their parent space. The pro of this approach is that all the rooms are in the room list, but the cons are that the member list and topic are inaccessible.

**Comment by q9f** [comment]
I was also thinking about adding another column on the left that allows toggling through spaces. The ranger idea is not bad. I would prefer that more than tags, however, this will eat even more of the screen space.

**Comment by Fell** [comment]
Why not make it a simple tree structure? 
```
Fruit Space
├Banana Chat
└Cherry Space └Room

**Comment by kqvanity** [comment]
An expandable space with a new full vim-centric redesign :rocket:
