### ISSUE TITLE
all gomuks users on multi-user systems attempt to read /tmp/gomuks/debug.log

### ISSUE THREAD

**Issue by akspecs** [tulir/gomuks#307]
the following takes place when another user attempts to run gomuks on a multi-user system:
```
panic: open /tmp/gomuks/debug.log: permission denied

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Initialize()
	/builds/tulir/gomuks/debug/debug.go:51 +0x43b
main.main()
	/builds/tulir/gomuks/main.go:48 +0x108
```
perhaps there's someway to instantiate a specific log per user that runs gomuks?

suggestion:
have gomuks create a unique directory to store debug.log in based on uid, or a randomly generated tmpfile, and make note of said tmpfile in the user's gomuks cache. if the tmpfile does not exist, create a new one and update the note of said tmpfile in the user's gomuks cache.

**Comment by akspecs** [comment]
a workaround:
a script or alias that runs
`TMPDIR="/tmp/gomuks-$USER" /usr/bin/gomuks`

**Comment by nileshpatra** [comment]
@tulir It'd be nice to get this implemented, as it'd make it much easier for people who use gomuks on a shared server for instance. You'll probably only have to tweak /tmp/gomuks with /tmp/gomuks-$(LOGNAME) or something else in the code. 

Since this issue has been open since ~2 years, could this get some action, please?

**Comment by nileshpatra** [comment]
Opened PR#428
