### ISSUE TITLE
Selection of the input-areas within the authenticative page does not invoke the keyboard when invoked by Android.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [tulir/gomuks#356]
Selection of the input-areas within the authenticative page does not invoke the keyboard when invoked by http://android.googlesource.com via "http://github.com/termux/termux-app".

**Comment by gi-yt** [comment]
gomuks is a cli program which can not interact with termux

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@gi-yt, should this consequently be reported to Termux?

**Comment by gi-yt** [comment]
no termux cannot get information from gomuks that you clicked on the thing.
you can toggle the keyboard if you swipe in the left iirc

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am doubtful that Termux is not able to ascertain that I have focused something that accepts input, because it appears to automatically invoke the keyboard when I focus the shell.

However, I am thankful for your information of how to manually invoke the keyboard, because that ability significantly lessens the importance of this problem.
