### ISSUE TITLE
Side panels take too much space with common default terminal sizes

### ISSUE THREAD

**Issue by guilevi** [tulir/gomuks#43]
On Mac OS 10.13 in built-in Terminal app, message display width seems to be only about 6 to 8 characters, making reading messages almost impossible.

**Comment by tulir** [comment]
The side panels don't properly adapt to the terminal size yet, and the current default panel sizes are such that the default terminal size doesn't really have enough space.

**Comment by retrotails** [comment]
I added an option to change the room panel's width using "/roomwidth (int)", it's just some lazy code for my personal use but it could be nice to have similar upstream. I have it set to 10 instead of the default 25 to save some space.
https://github.com/retrotails/gomuks/commit/e822d71696122db7c43964a09018cad17e4533a7
should probably also have a setting for the users list, but I always have that turned off so I didn't bother.
also, it was way easier than I thought for literally my first time using go. I think because of the angle brackets, the command usage thing prints some garbage, didn't actually try that until after I pushed.
